services:   
  db:
    image: postgres:latest
    ports:
      - 15432:5432
    environment:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=not-secure
      - POSTGRES_DB=hibernate-vs-jooq
      - POSTGRES_HOST_AUTH_METHOD=trust
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dbuser -d hibernate-vs-jooq"]
      interval: 5s
      timeout: 3s
      retries: 5

  backend-hibernate:
    profiles: [ "hibernate" ]
    build:
      context: ./backend-hibernate/
    container_name: backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/hibernate-vs-jooq
      - QUARKUS_DATASOURCE_USERNAME=dbuser
      - QUARKUS_DATASOURCE_PASSWORD=not-secure
    ports:
      - "8080:8080"

  backend-jooq:
    profiles: [ "jooq" ]
    build:
      context: ./backend-jooq/
    container_name: backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://db:5432/hibernate-vs-jooq
      - QUARKUS_DATASOURCE_USERNAME=dbuser
      - QUARKUS_DATASOURCE_PASSWORD=not-secure
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - BACKEND_URL=http://backend:8080
    ports:
      - "8081:8081"